import Navbar from "./components/Navbar";
import { AnimatePresence, motion } from "framer-motion";
import "./globals.css";
import {
  Pacifico,
  Montserrat,
  Dancing_Script,
  Caveat,
  Rampart_One,
} from "next/font/google";

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico",
});
const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mont",
});
const dancingScript = Dancing_Script({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-dancing-script",
});
const caveat = Caveat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-caveat",
});
const rampartOne = Rampart_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-rampart-one",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${pacifico.variable} ${montserrat.variable} ${dancingScript.variable} ${caveat.variable} ${rampartOne.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
